# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:

name: infra

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: debug secrets
      run: |
        echo "${{ secrets.RG }}"                | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.ASP }}"               | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.WEBAPP }}"            | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.LOC }}"               | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.AZURE_CREDENTIALS }}" | sed -r 's/(.)/\1 /g'
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          <TODO Azure CLI Service Plan>
          <TODO Azure CLI WebApp>
